name: gitleaks
on:
  pull_request:
  push:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 4 * * *" # run once a day at 4 AM
jobs:
  scan:
    name: gitleaks
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBT_TOKEN }}
  bash-example:
    needs: scan
    runs-on: self-hosted
    env:
      MY_NAME: "Mona The Octocat"
    steps:
      - uses: actions/checkout@v6
      - name: bash-version
        run: "bash"

    
  # sonarqube:
  #     needs: scan
  #     name: SonarQube Trigger
  #     runs-on: ubuntu-latest
  #     steps:
  #     - name: Checking out
  #       uses: actions/checkout@master
  #       with:
  #         # Disabling shallow clone is recommended for improving relevancy of reporting
  #         fetch-depth: 0
  #     - name: SonarQube Scan
  #       uses: kitabisa/sonarqube-action@v1.2.0
  #       with:
  #         host: ${{ secrets.SONARQUBE_HOST }}
  #         login: ${{ secrets.SONARQUBE_TOKEN }}


